name = "gumdrop"
type = "webpack"
workers_dev = true
webpack_config = "./worker/webpack.config.js"

[env.staging]
route = "gumdrop.averyharnish.com/*"

[env.prod]
route = "staging-gumdrop.averyharnish.com/*"

kv-namespaces = [ 
  { binding = "GUMDROP_FILES", id = "522fb3ade19548a7bd9a3d073f9f8448" } 
]

[site]
bucket = "www"
entry-point = "worker"
